### ISSUE TITLE
ECOINVENT_ORDERER_GEO in marginal-mixes

### ISSUE THREAD

**Issue by ljlazar** [IndEcol/wurst-examples#2]
Hi everyone,

first of all thanks a lot to the developers for sharing the very nice wurst-examples here, they are very impressive and helpful to me!

Running the marginal-mixes example, I am getting an error if importing "ECOINVENT_ORDERED_GEO" from wurst.ecoinvent (ImportError). I was unfortunately not able to find it anywhere in wurst. Is there a possibility to get access or generate it?

Thanks a lot for your help!

Best regards,
Lukas

**Comment by cmutel** [comment]
You are correct, this is missing in the `wurst` code, and I don't see it in the commit history. I suggest you contact the author, Laurent Vandepaer (laurentvandepaer@gmail.com), directly.

**Comment by lvandepaer** [comment]
Unfortunately, I cannot track down this function either. The notebooks were written when Wurst was still evolving a lot so things might have changed.

I would suggest to use the premise package to modify electricity mixes https://github.com/romainsacchi/premise  - It is a really great tool for prospective LCA and still maintained by a strong team :)  - otherwise the notebooks in https://pubs.acs.org/doi/abs/10.1021/acs.est.9b06484 which are more recent and more likely to work.
